### ISSUE TITLE
When I compile on Arduino it comes out this error

### ISSUE THREAD

**Issue by Adrenocortico** [thomasfredericks/Chrono#1]
Arduino:1.6.6 Hourly Build 2015/06/17 11:12 (Mac OS X), Board:"Arduino Uno"

/Chrono-master/Chrono.cpp: In member function 'void Chrono::delay(long unsigned int)':
/Chrono-master/Chrono.cpp:89:22: error: 'passed' was not declared in this scope
   while (!passed(time));
                      ^
/Chrono-master/Chrono.cpp: In member function 'bool Chrono::hasPassed(long unsigned int, bool) const':
/Chrono-master/Chrono.cpp: 100 :15: error: passing 'const Chrono' as 'this' argument of 'void Chrono::restart(long unsigned int)' discards qualifiers [-fpermissive]
       restart();
               ^

**Comment by thomasfredericks** [comment]
Thank you for this report. I believe the issue has been resolved.

**Comment by sofian** [comment]
I just downloaded the latest version and tested it and this problem no longer appears. Please try re-downloading the latest version.
