### ISSUE TITLE
Add Chrono ArduBadge Badge

### ISSUE THREAD

**Issue by gilmaimon** [thomasfredericks/Chrono#12]
Hi!
A nice addition to your readme page can be a this ardu-badge "badge" from [www.ardu-badge.com](http://www.ardu-badge.com/).
[![arduino-library-badge](http://www.ardu-badge.com/badge/Chrono.svg)](http://www.ardu-badge.com/Chrono)

Code:
`[![arduino-library-badge](http://www.ardu-badge.com/badge/Chrono.svg)](http://www.ardu-badge.com/Chrono)`

It shows:
1. That Chrono is in the "Library Manager" in the Arduino IDE 
2. The latest realease
3. Clicking on it redirects to a page with explanation on how to install the library.

What do you think?

**Comment by sofian** [comment]
Yes I think it'd be a good idea. What do you think @thomasfredericks ?

**Comment by thomasfredericks** [comment]
Done
