### ISSUE TITLE
myChrono.start()

### ISSUE THREAD

**Issue by jacobglasgow** [thomasfredericks/Chrono#3]
Hi,

I am trying to use the chrono library to make an arduino longterm countdown. When I compile the code, it is saying 'class Chrono' has no member named 'start' . Is there an obvious mistake I am making here?

Thanks

**Comment by thomasfredericks** [comment]
You are right. I am sorry. We changed that behavior. You have to use restart(). I will have to decide how to fix it.

**Comment by thomasfredericks** [comment]
start() was re-added and is the same as restart()
