### ISSUE TITLE
Chrono Timer(Chrono::SECONDS, false);

### ISSUE THREAD

**Issue by vangalvin** [thomasfredericks/Chrono#6]
Setting the timer so it will not start does not seem to work. Is this the correct way to implement it?

I am using the latest version but getting this

exit status 1
no matching function for call to 'Chrono::Chrono(Chrono::Resolution, bool)'

**Comment by BPDanek** [comment]
You could use the stop() function, and then call reset() when you need to start timing. The documentation suggests the timer is starts upon instantiation by design.

**Comment by sofian** [comment]
That's strange, it should work. Can you send me an example code so I can reproduce the bug?

**Comment by sofian** [comment]
In fact you are right, the constructor with Resolution enum does not allow for the startNow option. Let me see if I can fix this.

**Comment by sofian** [comment]
This has been fixed in the new release (v1.2.0).
